name: lugarlang
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.5
  permission_handler: ^10.2.0
  xml: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Iloilo City LPTRP - ROUTE 01 to ROUTE 08.kml
    - assets/Iloilo City LPTRP - ROUTE 09 to ROUTE 16.kml
    - assets/Iloilo City LPTRP - ROUTE 17 to ROUTE 24.kml
